resource_group_name = "#{TF_VAR_resource_group_name}#"
location = "#{TF_VAR_location}#"
storage_account_name = "#{TF_VAR_storage_account_name}#"
admin_username = "#{adminusername}#"
admin_password = "#{adminpassword}#"
admin_ssh_public_key = "#{sshkey}#"